// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_VkF0Xv-h0OrooV4l6Yt-4Ynv8hLTzUc',
    appId: '1:428423848290:web:b89d0a9aeb8d4a0804cc3b',
    messagingSenderId: '428423848290',
    projectId: 'chatapp-tutorial-f8d2b',
    authDomain: 'chatapp-tutorial-f8d2b.firebaseapp.com',
    storageBucket: 'chatapp-tutorial-f8d2b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfinwJw-mP6jRGU4pKHqLogBmIOp6D-lk',
    appId: '1:428423848290:android:1877ea2d507d1a3804cc3b',
    messagingSenderId: '428423848290',
    projectId: 'chatapp-tutorial-f8d2b',
    storageBucket: 'chatapp-tutorial-f8d2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhcB17ZyU6dR708lDid0HZsLegjKPIpeg',
    appId: '1:428423848290:ios:8623abaae87578eb04cc3b',
    messagingSenderId: '428423848290',
    projectId: 'chatapp-tutorial-f8d2b',
    storageBucket: 'chatapp-tutorial-f8d2b.appspot.com',
    iosBundleId: 'com.example.kabumChatbot',
  );

}